-- sport DB 생성
CREATE DATABASE sport default CHARACTER SET UTF8;
-- 만들어진 DB 사용하기
SHOW DATABASES;
-- DB 사용하기
use sport;
show tables;

-- 체육관 시설 리스트
create table t_fac_list(
	SEQ			BIGINT 			PRIMARY KEY	AUTO_INCREMENT,
	FAC_CD		VARCHAR(4)		NOT NULL,
	FAC_NM		VARCHAR(255)	NOT NULL,
	FAC_TEL		VARCHAR(11)		NULL,
	FAC_ADDR	VARCHAR(255)	NOT NULL,
	FAC_MONEY 	VARCHAR(1)		NOT NULL,
	FAC_SPORT	VARCHAR(2)		NOT NULL
);

-- user 테이블
create table t_user(
	SEQ					BIGINT 			PRIMARY KEY 				AUTO_INCREMENT,
	RGST_DT				DATETIME 		DEFAULT CURRENT_TIMESTAMP,
	RGST_ID				VARCHAR(20)		NOT NULL,	
	RVSE_DT				DATETIME 		DEFAULT CURRENT_TIMESTAMP,
	RVSE_ID				VARCHAR(20)		NOT NULL,
    USE_YN				VARCHAR(1)		DEFAULT 'Y',
	U_ID				VARCHAR(30)		NOT NULL,
	U_PW				VARCHAR(20)		NULL,
	U_NM				VARCHAR(60)		NULL,
	U_ADDR				VARCHAR(200)	NULL,
	U_DTLS_ADDR			VARCHAR(10)		NULL,
	U_TEL				VARCHAR(20)		NULL,
	U_CERT_KEY_ENC_VAL	VARCHAR(1000)	NULL
);

-- qna 테이블
create table t_qna(
	SEQ			BIGINT 			PRIMARY KEY 				AUTO_INCREMENT,
	RGST_DT		DATETIME 		DEFAULT CURRENT_TIMESTAMP,
	RGST_ID		VARCHAR(20)		NOT NULL,	
	RVSE_DT		DATETIME 		DEFAULT CURRENT_TIMESTAMP,
	RVSE_ID		VARCHAR(20)		NOT NULL,
    USE_YN		VARCHAR(1)		default 'Y',
	USER_ID		VARCHAR(30)		NOT NULL,	
	Q_TITLE_NM	VARCHAR(100)	NULL,
	Q_CTT		VARCHAR(255)	NULL,
	Q_NTC_YN	VARCHAR(1)		default 'N',
	Q_CLK_CNT	BIGINT			NOT NULL
);